server:
  port: 10000

spring:
  data:
    mongodb:
      uri: #private
      database: #private

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000





