server:
  port: 8081

spring:
  data:
    mongodb:
      uri: mongodb+srv://damian:oRAhCnuhtl3g9138@cluster0.dzyi1is.mongodb.net/clients_data
      database: clients_data


#  okta:
#    oauth2:
#      issuer: https://dev-....okta.com/oauth2/default
  main:
    allow-bean-definition-overriding: true
#  level:
#    root: INFO
#    org.springframework.web: INFO
#    org.springframework.security: INFO
#    org.springframework.security.oauth2: INFO

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080



