server:
  port: 10000

spring:
  data:
    mongodb:
      uri: mongodb+srv://damian:oRAhCnuhtl3g9138@cluster0.dzyi1is.mongodb.net/clients_data
      database: clients_data

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000





